### PR TITLE
Fix "go to label" in bazel LSP

### PR DESCRIPTION
**Pull request by cameron-martin**
When executing "go to definition" on a label, it would previously go to the correct file but not to the definition of that target. This was because we were searching for a function call where the name is the whole label. Now it parses the label, using the label parser introduced in #101, to extract the name and searches using that.

### CODE REVIEW

**Comment by stagnation** [comment]
Nice! Works for me.

**Comment by cameron-martin** [comment]
That's strange. It works for going to external repositories for me, just not when in a file in an external repository.

**Comment by stagnation** [comment]
Good! My bad, I had the runfiles library as the abbreviated package-only label. With `runfiles:runfiles` it does work!

**Comment by cameron-martin** [comment]
With #101 I will be able to fix this problem

**Comment by ndmitchell** [comment]
Any reason not to undraft this?

**Comment by cameron-martin** [comment]
> Any reason not to undraft this?

Yep I was waiting for the label parser to go in so I could use it here. I'll update this soon and undraft it.

**Comment by cameron-martin** [comment]
@ndmitchell This should be now good to go!

**Pull request closed without merging**
